### ISSUE TITLE
PDF Report Download Error Message

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/epic-engage#14]
Description: When a Team Member downloads an engagement's Public Report to PDF using Chrome, an error message appears and they cannot get the report.

Steps to Reproduce:

Open on Chrome
Engagements > Action Dropdown 
View Public Report > Export to PDF
Watch screen for download % > error message appears, screenshot attached

Actual Result: The PDF appear to download, but then an error message appears instead, no report opens in new tab

Environment: DEV, TEST. PROD

OS: Windows
Device/Model: Lenovo ThinkPad Laptop
Browser (if applicable): Chrome

Attachments:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54203431f1209f2a9a27309d96d87ab8c3707d3e/MicrosoftTeams-image%20%287%29.png)

**Comment by VineetBala-AOT** [comment]
@carlygreenehill , I tested this on different browsers but not able to reproduce the issue. It seems to be working fine. Can you please try and let me know if the issue is still happening.

**Comment by carlygreenehill** [comment]
@VineetBala-AOT  i'm checking in with the original bug hunter :) i will also try chrome from my home computer tonight. will report back by end of day!
