### ISSUE TITLE
All answer options should appear in the report (in order), not only the ones who have been selected by the public

### ISSUE THREAD

**Issue by marieanik** [bcgov/epic-engage#18]
Current behaviour: The report currently displays only the possible answer to a question the public has selected. 

For example, on survey Test Save Survey 2 - Nov 12, the report should display the option "0-20" for the question "3rd time edited age question" and "No" for the question "Third time edited Checkbox".

Solution: Display all the possible options for each question on the report, even if that option hasn't been selected yet. The option will then display 0 as the number of times this option was selected. All options should be displayed in the same order they appear in the survey.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWp3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81adfc227be783ff6e89d02623fcde3503b031cf/Screenshot%202023-11-20%20at%2010.38.16%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZ3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efa58549190ee9db94302da6121fd4656e563b59/Screenshot%202023-11-20%20at%2010.37.24%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW53QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5fa80361df9bf7c1e01a828a7f0ce7a49f7101f/Screenshot%202023-11-20%20at%2010.37.34%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJ3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1e2451e31f3d01ef57efa0f766c76b14947a7fa/Screenshot%202023-11-20%20at%2010.38.09%20AM.png)

**Comment by VineetBala-AOT** [comment]
Changes deployed to production.
