### ISSUE TITLE
Live Activity Counts displaying incorrectly

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/epic-engage#2]
Description: The Live Activity count, as part of the Internal and Public Reports, is showing activity prior to the Engagement Page being published & live to the public. 

Summary: There is a count of "2" for August 2023 and "2" for September 2023, but the page wasn't published until October 4. 
Steps to Reproduce: 
1. Engagements > look to Coyote Hydrogen - Early Engagement 
2. Hit Actions dropdown > select View Report - Public or Internal
3. Scroll to see Live Activity > notice August/September

Expected Result: There should only be Live Activity since the Engagement Page went live
Actual Result: There are 4 counts of mystery data, appearing under August/September, which should not be possible
Environment: PROD

OS: Windows
Device/Model: Lenovo ThinkPad Laptop
Browser (if applicable): Edge
Attachments: 
![image](https://github.com/bcgov/epic-engage/assets/101662408/07990820-1759-455c-af90-d31dde7b3fdc)

**Comment by VineetBala-AOT** [comment]
Obsolete data in the system, erroneously being included in this survey result, has been successfully purged and rectified.
