### ISSUE TITLE
Read all comments on report: Questions are not displayed on public "Read Comments" 

### ISSUE THREAD

**Issue by marieanik** [bcgov/epic-engage#22]
The current "Read all comments" section on the reports does not include the questions associated with the comments. We need to display the question above the comments as we do in the internal "Read All Comments" section. The date should also be the same size as the comments font-size.  (16px, not h6)
Current:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDMzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f8c9ea6e5e7a48e9b5f41fbda4c3d70576caed6/Screenshot%202023-11-20%20at%2011.01.54%20AM.png)

Should be :
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUQzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c561880e0814a0de2fdb8f18a0016d5e8ae0ffa1/Screenshot%202023-11-21%20at%2010.10.25%20AM.png)

**Comment by VineetBala-AOT** [comment]
Changes deployed to production.
