### ISSUE TITLE
Changes required to the Public/Proponent csv

### ISSUE THREAD

**Issue by marieanik** [bcgov/epic-engage#26]
We should evaluate the work required to change the format to an excel spreadsheet rather than a csv.

Here are the changes required:
- Randomize the comments in alphabetical order
- Remove the empty cells so all the comments are stacked together just below the question
- Add a "Proponent Answer" column after each survey question column
**IF possible:**
- Format cells so the text wraps and cell are big enough to accomodate all the text
- Formatted Header/Question row with questions in bold and background color (can be done by admins but if we decide to go for Excel, maybe this is possible)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c404d271a544c3cea1f4ba70a302b1f2fda9b035/Screenshot%202023-11-29%20at%204.15.57%20PM.png)

**Comment by VineetBala-AOT** [comment]
Changes deployed to production.
