### ISSUE TITLE
Internal/Public Reports show question results out of order

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/epic-engage#3]
Description: The Survey Results section of both the Internal and Public reports show results to question, but the questions appear in a different order than sequenced in the survey

Summary: If a staff or public user would view the report, they would likely expect to view Results in an order similar to how they answered them on the original survey.

Steps to Reproduce:

1. Engagements > look to Coyote Hydrogen - Early Engagement 
2. Hit Actions dropdown > select View Report - Public or Internal
3. Scroll to Survey Results > notice that the first question displayed is actually part of a Likert Matrix from Q4 ['Outreach' page 2], the next result displayed is from a question which is actually Q15ish? [from 'Project Location' page 4] on the survey, etc.

Expected Result: The results should display in the same order they're listed on the survey, including the sub questions in Likert matrixes
Actual Result: The results are in an apparent random order
Environment: PROD

OS: Windows
Device/Model: Lenovo ThinkPad Laptop
Browser (if applicable): Edge

Attachments:

Results

![image](https://github.com/bcgov/epic-engage/assets/101662408/7603dea9-2013-4183-8425-209df5fe4533)

First Page of Survey

![image](https://github.com/bcgov/epic-engage/assets/101662408/6e89cd4e-3a72-4708-b060-a891195c5257)

**Comment by VineetBala-AOT** [comment]
Rectified data inconsistencies in existing survey results and deployed a code fix to address the underlying issue for future survey instances.
