### ISSUE TITLE
BUG - Report - 'Surveys Completed' animation is wrong

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/epic-engage#38]
Description: On the live report and PDF, the "Surveys Completed" animation/graphic is a full ring, indicated 100%, where it should be reflect the proportion of surveys completed out of total surveys sent.

Steps to Reproduce:

Open on Edge
Engagements > Action Dropdown [I was looking at Fraser River Tunnel Project]
View Public Report (see it here or) > Export to PDF

Actual Result: Animation goes to "100%" mark

Environment: just looked for it in PROD so far

OS: Windows
Device/Model: Lenovo ThinkPad Laptop
Browser (if applicable): Edge

Attachments:

<img width="1375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMngwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--097385fc71e638a1054a9949c7cc8d3a181a0ab7/image.png" alt="image.png" />

**Comment by carlygreenehill** [comment]
@VineetBala-AOT found a new bug!

**Comment by VineetBala-AOT** [comment]
@carlygreenehill , we have defined the maximum number of submissions to be 100 for one engagement as a result when it gets to a closer number it fills up the complete circle. We can increase it if you could suggest a threshold number.

**Comment by VineetBala-AOT** [comment]
Made change such that the Survey Emails Sent will always be completely filled in but Surveys Completed will be partially measured against the Survey Emails Sent. In case all submissions happen for Survey Emails Sent then both the circles will be completely filled in. Charts will now look like below: 

![image](https://github.com/bcgov/epic-engage/assets/90332175/261049bc-4320-4b0c-96d7-cd69e08b7b05)

CC: @carlygreenehill
